export const CSGOdata = [
  {
    PlayerId: 3883,
    NameFirst: "Peter",
    NameLast: "Rasmussen",
    CurrentHandle: "dupreeh",
    CountryCode: "dk",
    TotalUSDPrize: "2181164.40",
    ImageURL: "CSGOPlayerImages/dupreeh.jpg",
  },
  {
    PlayerId: 3679,
    NameFirst: "Andreas",
    NameLast: "H\u00f8jsleth",
    CurrentHandle: "Xyp9x",
    CountryCode: "dk",
    TotalUSDPrize: "1998046.89",
    ImageURL: "CSGOPlayerImages/Xyp9x.jpg",
  },
  {
    PlayerId: 3885,
    NameFirst: "Nicolai",
    NameLast: "Reedtz",
    CurrentHandle: "dev1ce",
    CountryCode: "dk",
    TotalUSDPrize: "1957031.54",
    ImageURL: "CSGOPlayerImages/dev1ce.jpg",
  },
  {
    PlayerId: 3672,
    NameFirst: "Lukas",
    NameLast: "Rossander",
    CurrentHandle: "gla1ve",
    CountryCode: "dk",
    TotalUSDPrize: "1869042.41",
    ImageURL: "CSGOPlayerImages/gla1ve.jpg",
  },
  {
    PlayerId: 17800,
    NameFirst: "Emil",
    NameLast: "Reif",
    CurrentHandle: "Magisk",
    CountryCode: "dk",
    TotalUSDPrize: "1774623.63",
    ImageURL: "CSGOPlayerImages/Magisk.jpg",
  },
  {
    PlayerId: 8169,
    NameFirst: "Alexander",
    NameLast: "Kostylev",
    CurrentHandle: "s1mple",
    CountryCode: "ua",
    TotalUSDPrize: "1718388.65",
    ImageURL: "CSGOPlayerImages/s1mple.jpg",
  },
  {
    PlayerId: 2452,
    NameFirst: "Finn",
    NameLast: "Andersen",
    CurrentHandle: "karrigan",
    CountryCode: "dk",
    TotalUSDPrize: "1635052.06",
    ImageURL: "CSGOPlayerImages/karrigan.jpg",
  },
  {
    PlayerId: 16267,
    NameFirst: "Denis",
    NameLast: "Sharipov",
    CurrentHandle: "electroNic",
    CountryCode: "ru",
    TotalUSDPrize: "1572125.33",
    ImageURL: "CSGOPlayerImages/electroNic.jpg",
  },
  {
    PlayerId: 20415,
    NameFirst: "Russel",
    NameLast: "Van Dulken",
    CurrentHandle: "Twistzz",
    CountryCode: "ca",
    TotalUSDPrize: "1524593.10",
    ImageURL: "CSGOPlayerImages/Twistzz.jpg",
  },
  {
    PlayerId: 5483,
    NameFirst: "H\u00e5vard",
    NameLast: "Nygaard",
    CurrentHandle: "rain",
    CountryCode: "no",
    TotalUSDPrize: "1427516.24",
    ImageURL: "CSGOPlayerImages/rain.jpg",
  },
  {
    PlayerId: 10629,
    NameFirst: "Keith",
    NameLast: "Markovic",
    CurrentHandle: "NAF",
    CountryCode: "ca",
    TotalUSDPrize: "1217282.06",
    ImageURL: "CSGOPlayerImages/NAF.jpg",
  },
  {
    PlayerId: 5783,
    NameFirst: "Nikola",
    NameLast: "Kova\u010d",
    CurrentHandle: "NiKo",
    CountryCode: "ba",
    TotalUSDPrize: "1193369.23",
    ImageURL: "CSGOPlayerImages/NiKo.jpg",
  },
  {
    PlayerId: 3888,
    NameFirst: "Dan",
    NameLast: "Madesclaire",
    CurrentHandle: "apEX",
    CountryCode: "fr",
    TotalUSDPrize: "1191619.05",
    ImageURL: "CSGOPlayerImages/apEX.jpg",
  },
  {
    PlayerId: 16800,
    NameFirst: "Jakey",
    NameLast: "Yip",
    CurrentHandle: "Stewie2k",
    CountryCode: "us",
    TotalUSDPrize: "1186573.20",
    ImageURL: "CSGOPlayerImages/Stewie2k.jpg",
  },
  {
    PlayerId: 49589,
    NameFirst: "Ilya",
    NameLast: "Zalutskiy",
    CurrentHandle: "Perfecto",
    CountryCode: "ru",
    TotalUSDPrize: "1170037.44",
    ImageURL: "CSGOPlayerImages/Perfecto.jpg",
  },
  {
    PlayerId: 11788,
    NameFirst: "Jonathan",
    NameLast: "Jablonowski",
    CurrentHandle: "ELiGE",
    CountryCode: "us",
    TotalUSDPrize: "1165212.82",
    ImageURL: "CSGOPlayerImages/ELiGE.jpg",
  },
  {
    PlayerId: 31594,
    NameFirst: "Robin",
    NameLast: "Kool",
    CurrentHandle: "ropz",
    CountryCode: "ee",
    TotalUSDPrize: "1164827.41",
    ImageURL: "CSGOPlayerImages/ropz.jpg",
  },
  {
    PlayerId: 2455,
    NameFirst: "Gabriel",
    NameLast: "Toledo",
    CurrentHandle: "FalleN",
    CountryCode: "br",
    TotalUSDPrize: "1164186.54",
    ImageURL: "CSGOPlayerImages/FalleN.jpg",
  },
  {
    PlayerId: 36982,
    NameFirst: "Kirill Sergeyevich",
    NameLast: "Mikhailov",
    CurrentHandle: "Boombl4",
    CountryCode: "ru",
    TotalUSDPrize: "1100699.87",
    ImageURL: "CSGOPlayerImages/Boombl4.jpg",
  },
  {
    PlayerId: 12183,
    NameFirst: "Epit\u00e1cio",
    NameLast: "de Melo",
    CurrentHandle: "TACO",
    CountryCode: "br",
    TotalUSDPrize: "1095886.48",
    ImageURL: "CSGOPlayerImages/TACO.jpg",
  },
  {
    PlayerId: 12169,
    NameFirst: "Fernando",
    NameLast: "Alvarenga",
    CurrentHandle: "fer",
    CountryCode: "br",
    TotalUSDPrize: "1077986.54",
    ImageURL: "CSGOPlayerImages/fer.jpg",
  },
  {
    PlayerId: 8635,
    NameFirst: "Nicholas",
    NameLast: "Cannella",
    CurrentHandle: "nitr0",
    CountryCode: "us",
    TotalUSDPrize: "1058468.13",
    ImageURL: "CSGOPlayerImages/nitr0.jpg",
  },
  {
    PlayerId: 73128,
    NameFirst: "Valeriy Yevheniiovych",
    NameLast: "Vakhovskiy",
    CurrentHandle: "B1t",
    CountryCode: "ua",
    TotalUSDPrize: "1048991.03",
    ImageURL: "CSGOPlayerImages/B1t.jpeg",
  },
  {
    PlayerId: 12182,
    NameFirst: "Marcelo",
    NameLast: "David",
    CurrentHandle: "coldzera",
    CountryCode: "br",
    TotalUSDPrize: "1046101.46",
    ImageURL: "CSGOPlayerImages/coldzera.jpg",
  },
  {
    PlayerId: 5000,
    NameFirst: "Freddy",
    NameLast: "Johansson",
    CurrentHandle: "KRiMZ",
    CountryCode: "se",
    TotalUSDPrize: "953761.90",
    ImageURL: "CSGOPlayerImages/KRiMZ.jpg",
  },
  {
    PlayerId: 3875,
    NameFirst: "Jesper",
    NameLast: "Wecksell",
    CurrentHandle: "JW",
    CountryCode: "se",
    TotalUSDPrize: "919744.62",
    ImageURL: "CSGOPlayerImages/JW.jpeg",
  },
  {
    PlayerId: 5001,
    NameFirst: "Olof",
    NameLast: "Kajbjer",
    CurrentHandle: "olofmeister",
    CountryCode: "se",
    TotalUSDPrize: "917714.60",
    ImageURL: "CSGOPlayerImages/olofmeister.jpg",
  },
  {
    PlayerId: 3878,
    NameFirst: "Robin",
    NameLast: "R\u00f6nnquist",
    CurrentHandle: "flusha",
    CountryCode: "se",
    TotalUSDPrize: "886552.89",
    ImageURL: "CSGOPlayerImages/flusha.jpg",
  },
  {
    PlayerId: 8168,
    NameFirst: "Egor",
    NameLast: "Vasilyev",
    CurrentHandle: "flamie",
    CountryCode: "ru",
    TotalUSDPrize: "872953.41",
    ImageURL: "CSGOPlayerImages/flamie.jpg",
  },
  {
    PlayerId: 3290,
    NameFirst: "Nathan",
    NameLast: "Schmitt",
    CurrentHandle: "NBK",
    CountryCode: "fr",
    TotalUSDPrize: "828938.17",
    ImageURL: "CSGOPlayerImages/NBK.jpg",
  },
  {
    PlayerId: 54188,
    NameFirst: "Helvijs",
    NameLast: "Saukants",
    CurrentHandle: "broky",
    CountryCode: "lv",
    TotalUSDPrize: "810132.41",
    ImageURL: "CSGOPlayerImages/broky.jpg",
  },
  {
    PlayerId: 3881,
    NameFirst: "Richard",
    NameLast: "Papillon",
    CurrentHandle: "shox",
    CountryCode: "fr",
    TotalUSDPrize: "809307.08",
    ImageURL: "CSGOPlayerImages/shox.jpg",
  },
  {
    PlayerId: 3882,
    NameFirst: "Ladislav",
    NameLast: "Kov\u00e1cs",
    CurrentHandle: "GuardiaN",
    CountryCode: "sk",
    TotalUSDPrize: "802435.95",
    ImageURL: "CSGOPlayerImages/GuardiaN.jpg",
  },
  {
    PlayerId: 25121,
    NameFirst: "Abay",
    NameLast: "Khasenov",
    CurrentHandle: "HObbit",
    CountryCode: "kz",
    TotalUSDPrize: "796641.25",
    ImageURL: "CSGOPlayerImages/HObbit.jpg",
  },
  {
    PlayerId: 10630,
    NameFirst: "Tarik",
    NameLast: "Celik",
    CurrentHandle: "tarik",
    CountryCode: "us",
    TotalUSDPrize: "791539.21",
    ImageURL: "CSGOPlayerImages/tarik.jpg",
  },
  {
    PlayerId: 3289,
    NameFirst: "Kenny",
    NameLast: "Schrub",
    CurrentHandle: "kennyS",
    CountryCode: "fr",
    TotalUSDPrize: "734398.91",
    ImageURL: "CSGOPlayerImages/kennyS.jpg",
  },
  {
    PlayerId: 31001,
    NameFirst: "Mathieu",
    NameLast: "Herbaut",
    CurrentHandle: "ZywOo",
    CountryCode: "fr",
    TotalUSDPrize: "710677.81",
    ImageURL: "CSGOPlayerImages/ZywOo.jpeg",
  },
  {
    PlayerId: 1511,
    NameFirst: "Daniil",
    NameLast: "Teslenko",
    CurrentHandle: "Zeus",
    CountryCode: "ua",
    TotalUSDPrize: "689568.70",
    ImageURL: "CSGOPlayerImages/Zeus.jpg",
  },
  {
    PlayerId: 4998,
    NameFirst: "Janusz",
    NameLast: "Pogorzelski",
    CurrentHandle: "snax",
    CountryCode: "pl",
    TotalUSDPrize: "674887.89",
    ImageURL: "CSGOPlayerImages/snax.jpg",
  },
  {
    PlayerId: 4311,
    NameFirst: "Will",
    NameLast: "Wierzba",
    CurrentHandle: "Rush",
    CountryCode: "us",
    TotalUSDPrize: "634476.87",
    ImageURL: "CSGOPlayerImages/Rush.jpg",
  },
  {
    PlayerId: 10736,
    NameFirst: "Markus",
    NameLast: "Kj\u00e6rbye",
    CurrentHandle: "Kjaerbye",
    CountryCode: "dk",
    TotalUSDPrize: "623296.93",
    ImageURL: "CSGOPlayerImages/Kjaerbye.jpg",
  },
  {
    PlayerId: 1485,
    NameFirst: "Filip",
    NameLast: "Kubski",
    CurrentHandle: "neo",
    CountryCode: "pl",
    TotalUSDPrize: "617331.01",
    ImageURL: "CSGOPlayerImages/neo.jpg",
  },
  {
    PlayerId: 1510,
    NameFirst: "Ioann",
    NameLast: "Sukharev",
    CurrentHandle: "Edward",
    CountryCode: "ua",
    TotalUSDPrize: "615858.02",
    ImageURL: "CSGOPlayerImages/Edward.jpg",
  },
  {
    PlayerId: 48581,
    NameFirst: "Vladislav",
    NameLast: "Gorshkov",
    CurrentHandle: "nafany",
    CountryCode: "ru",
    TotalUSDPrize: "608833.92",
    ImageURL: "CSGOPlayerImages/nafany.jpg",
  },
  {
    PlayerId: 63706,
    NameFirst: "Dmitry",
    NameLast: "Sokolov",
    CurrentHandle: "sh1ro",
    CountryCode: "ru",
    TotalUSDPrize: "608833.92",
    ImageURL: "CSGOPlayerImages/sh1ro.jpg",
  },
  {
    PlayerId: 3951,
    NameFirst: "Chris",
    NameLast: "de Jong",
    CurrentHandle: "chrisJ",
    CountryCode: "nl",
    TotalUSDPrize: "608248.79",
    ImageURL: "CSGOPlayerImages/chrisJ.jpg",
  },
  {
    PlayerId: 49036,
    NameFirst: "Sergey",
    NameLast: "Rykhtorov",
    CurrentHandle: "Ax1Le",
    CountryCode: "ru",
    TotalUSDPrize: "608030.28",
    ImageURL: "CSGOPlayerImages/Ax1Le.jpg",
  },
  {
    PlayerId: 1484,
    NameFirst: "Wiktor",
    NameLast: "Wojtas",
    CurrentHandle: "TaZ",
    CountryCode: "pl",
    TotalUSDPrize: "602078.30",
    ImageURL: "CSGOPlayerImages/TaZ.jpg",
  },
  {
    PlayerId: 20727,
    NameFirst: "Nemanja",
    NameLast: "Kova\u010d",
    CurrentHandle: "huNter",
    CountryCode: "ba",
    TotalUSDPrize: "592300.65",
    ImageURL: "CSGOPlayerImages/huNter.jpg",
  },
  {
    PlayerId: 43114,
    NameFirst: "Rasmus",
    NameLast: "Beck",
    CurrentHandle: "sjuush",
    CountryCode: "dk",
    TotalUSDPrize: "586063.09",
    ImageURL: "CSGOPlayerImages/sjuush.jpg",
  },
  {
    PlayerId: 5034,
    NameFirst: "Casper",
    NameLast: "M\u00f8ller",
    CurrentHandle: "cadiaN",
    CountryCode: "dk",
    TotalUSDPrize: "583145.73",
    ImageURL: "CSGOPlayerImages/cadiaN.jpg",
  },
  {
    PlayerId: 4997,
    NameFirst: "Pawe\u0142",
    NameLast: "Bieli\u0144ski",
    CurrentHandle: "byali",
    CountryCode: "pl",
    TotalUSDPrize: "582459.93",
    ImageURL: "CSGOPlayerImages/byali.jpg",
  },
  {
    PlayerId: 1488,
    NameFirst: "Jaros\u0142aw",
    NameLast: "Jarz\u0105bkowski",
    CurrentHandle: "pashaBiceps",
    CountryCode: "pl",
    TotalUSDPrize: "578384.06",
    ImageURL: "CSGOPlayerImages/pashaBiceps.jpg",
  },
  {
    PlayerId: 1490,
    NameFirst: "Patrik",
    NameLast: "Lindberg",
    CurrentHandle: "f0rest",
    CountryCode: "se",
    TotalUSDPrize: "571133.78",
    ImageURL: "CSGOPlayerImages/f0rest.jpg",
  },
  {
    PlayerId: 39608,
    NameFirst: "Alexey",
    NameLast: "Golubev",
    CurrentHandle: "Qikert",
    CountryCode: "kz",
    TotalUSDPrize: "557154.13",
    ImageURL: "CSGOPlayerImages/Qikert.jpg",
  },
  {
    PlayerId: 35077,
    NameFirst: "Ali",
    NameLast: "Dzhami",
    CurrentHandle: "Jame",
    CountryCode: "ru",
    TotalUSDPrize: "554867.72",
    ImageURL: "CSGOPlayerImages/Jame.jpeg",
  },
  {
    PlayerId: 10485,
    NameFirst: "Justin",
    NameLast: "Savage",
    CurrentHandle: "jks",
    CountryCode: "au",
    TotalUSDPrize: "554751.43",
    ImageURL: "CSGOPlayerImages/jks.png",
  },
  {
    PlayerId: 40798,
    NameFirst: "Timofey",
    NameLast: "Yakushin",
    CurrentHandle: "interz",
    CountryCode: "ru",
    TotalUSDPrize: "542076.34",
    ImageURL: "CSGOPlayerImages/interz.jpg",
  },
  {
    PlayerId: 33679,
    NameFirst: "Martin",
    NameLast: "Lund",
    CurrentHandle: "stavn",
    CountryCode: "dk",
    TotalUSDPrize: "525037.63",
    ImageURL: "CSGOPlayerImages/stavn.jpg",
  },
  {
    PlayerId: 3293,
    NameFirst: "C\u00e9dric",
    NameLast: "Guipouy",
    CurrentHandle: "RpK",
    CountryCode: "fr",
    TotalUSDPrize: "524870.95",
    ImageURL: "CSGOPlayerImages/RpK.jpg",
  },
  {
    PlayerId: 1492,
    NameFirst: "Christopher",
    NameLast: "Alesund",
    CurrentHandle: "GeT_RiGhT",
    CountryCode: "se",
    TotalUSDPrize: "519015.39",
    ImageURL: "CSGOPlayerImages/GeT_RiGhT.jpg",
  },
  {
    PlayerId: 18811,
    NameFirst: "Kristian",
    NameLast: "Wienecke",
    CurrentHandle: "k0nfig",
    CountryCode: "dk",
    TotalUSDPrize: "518805.81",
    ImageURL: "CSGOPlayerImages/k0nfig.jpg",
  },
  {
    PlayerId: 2440,
    NameFirst: "Richard",
    NameLast: "Landstr\u00f6m",
    CurrentHandle: "Xizt",
    CountryCode: "se",
    TotalUSDPrize: "513805.74",
    ImageURL: "CSGOPlayerImages/Xizt.jpg",
  },
  {
    PlayerId: 11483,
    NameFirst: "Peter",
    NameLast: "Jarguz",
    CurrentHandle: "stanislaw",
    CountryCode: "ca",
    TotalUSDPrize: "510120.72",
    ImageURL: "CSGOPlayerImages/stanislaw.jpg",
  },
  {
    PlayerId: 41398,
    NameFirst: "Rene",
    NameLast: "Madsen",
    CurrentHandle: "TeSeS",
    CountryCode: "dk",
    TotalUSDPrize: "509640.92",
    ImageURL: "CSGOPlayerImages/TeSeS.jpg",
  },
  {
    PlayerId: 35378,
    NameFirst: "Timur",
    NameLast: "Tulepov",
    CurrentHandle: "Buster",
    CountryCode: "kz",
    TotalUSDPrize: "491400.80",
    ImageURL: "CSGOPlayerImages/Buster.jpg",
  },
  {
    PlayerId: 3889,
    NameFirst: "Vincent",
    NameLast: "Schopenhauer",
    CurrentHandle: "Happy",
    CountryCode: "fr",
    TotalUSDPrize: "485910.46",
    ImageURL: "CSGOPlayerImages/Happy.jpg",
  },
  {
    PlayerId: 12859,
    NameFirst: "Jonas",
    NameLast: "Olofsson",
    CurrentHandle: "Lekr0",
    CountryCode: "se",
    TotalUSDPrize: "484880.51",
    ImageURL: "CSGOPlayerImages/Lekr0.jpg",
  },
  {
    PlayerId: 11938,
    NameFirst: "Timothy",
    NameLast: "Ta",
    CurrentHandle: "autimatic",
    CountryCode: "us",
    TotalUSDPrize: "463910.29",
    ImageURL: "CSGOPlayerImages/autimatic.jpg",
  },
  {
    PlayerId: 28556,
    NameFirst: "Maikil",
    NameLast: "Selim",
    CurrentHandle: "Golden",
    CountryCode: "se",
    TotalUSDPrize: "461342.48",
    ImageURL: "CSGOPlayerImages/Golden.jpg",
  },
  {
    PlayerId: 21291,
    NameFirst: "Fredrik",
    NameLast: "Sterner",
    CurrentHandle: "REZ",
    CountryCode: "se",
    TotalUSDPrize: "443411.65",
    ImageURL: "CSGOPlayerImages/REZ.jpg",
  },
  {
    PlayerId: 3752,
    NameFirst: "Tyler",
    NameLast: "Latham",
    CurrentHandle: "Skadoodle",
    CountryCode: "us",
    TotalUSDPrize: "436879.98",
    ImageURL: "CSGOPlayerImages/Skadoodle.jpg",
  },
  {
    PlayerId: 28489,
    NameFirst: "Vincent",
    NameLast: "Cayonte",
    CurrentHandle: "Brehze",
    CountryCode: "us",
    TotalUSDPrize: "430734.67",
    ImageURL: "CSGOPlayerImages/Brehze.jpg",
  },
  {
    PlayerId: 3287,
    NameFirst: "Adam",
    NameLast: "Friberg",
    CurrentHandle: "friberg",
    CountryCode: "se",
    TotalUSDPrize: "430065.49",
    ImageURL: "CSGOPlayerImages/friberg.jpg",
  },
  {
    PlayerId: 2450,
    NameFirst: "Aleksi",
    NameLast: "Jalli",
    CurrentHandle: "allu",
    CountryCode: "fi",
    TotalUSDPrize: "428487.87",
    ImageURL: "CSGOPlayerImages/allu.jpg",
  },
  {
    PlayerId: 3676,
    NameFirst: "Dauren",
    NameLast: "Kystaubayev",
    CurrentHandle: "AdreN",
    CountryCode: "kz",
    TotalUSDPrize: "424455.65",
    ImageURL: "CSGOPlayerImages/AdreN.jpg",
  },
  {
    PlayerId: 12179,
    NameFirst: "Ricardo",
    NameLast: "Prass",
    CurrentHandle: "boltz",
    CountryCode: "br",
    TotalUSDPrize: "421658.17",
    ImageURL: "CSGOPlayerImages/boltz.jpg",
  },
  {
    PlayerId: 6366,
    NameFirst: "Audric",
    NameLast: "Jug",
    CurrentHandle: "JaCkz",
    CountryCode: "fr",
    TotalUSDPrize: "419814.54",
    ImageURL: "CSGOPlayerImages/JaCkz.jpg",
  },
  {
    PlayerId: 4996,
    NameFirst: "Ren\u00e8",
    NameLast: "Borg",
    CurrentHandle: "cajunb",
    CountryCode: "dk",
    TotalUSDPrize: "418465.86",
    ImageURL: "CSGOPlayerImages/cajunb.jpg",
  },
  {
    PlayerId: 3952,
    NameFirst: "Johannes",
    NameLast: "Wodarz",
    CurrentHandle: "tabseN",
    CountryCode: "de",
    TotalUSDPrize: "417972.45",
    ImageURL: "CSGOPlayerImages/tabseN.jpeg",
  },
  {
    PlayerId: 13134,
    NameFirst: "\u0130smail\u0441an",
    NameLast: "D\u00f6rtkarde\u015f",
    CurrentHandle: "XANTARES",
    CountryCode: "tr",
    TotalUSDPrize: "416835.93",
    ImageURL: "CSGOPlayerImages/XANTARES.jpg",
  },
  {
    PlayerId: 37953,
    NameFirst: "Mareks",
    NameLast: "Ga\u013cinskis",
    CurrentHandle: "YEKINDAR",
    CountryCode: "lv",
    TotalUSDPrize: "415389.57",
    ImageURL: "CSGOPlayerImages/YEKINDAR.jpg",
  },
  {
    PlayerId: 30622,
    NameFirst: "Cvetelin",
    NameLast: "Nikolov",
    CurrentHandle: "CeRq",
    CountryCode: "bg",
    TotalUSDPrize: "412263.38",
    ImageURL: "CSGOPlayerImages/CeRq.jpg",
  },
  {
    PlayerId: 20813,
    NameFirst: "Aleksi",
    NameLast: "Virolainen",
    CurrentHandle: "Aleksib",
    CountryCode: "fi",
    TotalUSDPrize: "407191.03",
    ImageURL: "CSGOPlayerImages/Aleksib.jpg",
  },
  {
    PlayerId: 22335,
    NameFirst: "Nemanja",
    NameLast: "Isakovi\u0107",
    CurrentHandle: "nexa",
    CountryCode: "rs",
    TotalUSDPrize: "405321.50",
    ImageURL: "CSGOPlayerImages/nexa.jpg",
  },
  {
    PlayerId: 29711,
    NameFirst: "Ethan",
    NameLast: "Arnold",
    CurrentHandle: "Ethan",
    CountryCode: "us",
    TotalUSDPrize: "399880.38",
    ImageURL: "CSGOPlayerImages/Ethan.jpg",
  },
  {
    PlayerId: 2456,
    NameFirst: "Lincoln",
    NameLast: "Lau",
    CurrentHandle: "fnx",
    CountryCode: "br",
    TotalUSDPrize: "394779.80",
    ImageURL: "CSGOPlayerImages/fnx.jpg",
  },
  {
    PlayerId: 17622,
    NameFirst: "Francois",
    NameLast: "Delaunay",
    CurrentHandle: "Amanek",
    CountryCode: "fr",
    TotalUSDPrize: "394202.14",
    ImageURL: "CSGOPlayerImages/Amanek.jpg",
  },
  {
    PlayerId: 17801,
    NameFirst: "Valdemar",
    NameLast: "Vangs\u00e5",
    CurrentHandle: "Valde",
    CountryCode: "dk",
    TotalUSDPrize: "392356.37",
    ImageURL: "CSGOPlayerImages/Valde.jpg",
  },
  {
    PlayerId: 3998,
    NameFirst: "Fabien",
    NameLast: "Fiey",
    CurrentHandle: "KIOSHIMA",
    CountryCode: "fr",
    TotalUSDPrize: "378804.11",
    ImageURL: "CSGOPlayerImages/KIOSHIMA.jpg",
  },
  {
    PlayerId: 24832,
    NameFirst: "David",
    NameLast: "\u010cer\u0148ansk\u00fd",
    CurrentHandle: "frozen",
    CountryCode: "sk",
    TotalUSDPrize: "374131.99",
    ImageURL: "CSGOPlayerImages/frozen.jpg",
  },
  {
    PlayerId: 5472,
    NameFirst: "Tom\u00e1\u0161",
    NameLast: "\u0160\u0165astn\u00fd",
    CurrentHandle: "oskar",
    CountryCode: "cz",
    TotalUSDPrize: "370309.44",
    ImageURL: "CSGOPlayerImages/oskar.jpg",
  },
  {
    PlayerId: 2494,
    NameFirst: "Dennis",
    NameLast: "Edman",
    CurrentHandle: "dennis",
    CountryCode: "se",
    TotalUSDPrize: "366702.68",
    ImageURL: "CSGOPlayerImages/dennis.jpg",
  },
  {
    PlayerId: 12173,
    NameFirst: "Jo\u00e3o",
    NameLast: "Vasconcellos",
    CurrentHandle: "felps",
    CountryCode: "br",
    TotalUSDPrize: "363355.43",
    ImageURL: "CSGOPlayerImages/felps.jpg",
  },
  {
    PlayerId: 5433,
    NameFirst: "Martin",
    NameLast: "Styk",
    CurrentHandle: "STYKO",
    CountryCode: "sk",
    TotalUSDPrize: "363202.41",
    ImageURL: "CSGOPlayerImages/STYKO.jpeg",
  },
  {
    PlayerId: 37663,
    NameFirst: "Ludvig",
    NameLast: "Brolin",
    CurrentHandle: "Brollan",
    CountryCode: "se",
    TotalUSDPrize: "353125.84",
    ImageURL: "CSGOPlayerImages/Brollan.jpg",
  },
  {
    PlayerId: 3673,
    NameFirst: "Mathias",
    NameLast: "Lauridsen",
    CurrentHandle: "MSL",
    CountryCode: "dk",
    TotalUSDPrize: "349442.38",
    ImageURL: "CSGOPlayerImages/MSL.jpg",
  },
  {
    PlayerId: 4587,
    NameFirst: "Denis",
    NameLast: "Kostin",
    CurrentHandle: "seized",
    CountryCode: "ru",
    TotalUSDPrize: "346710.81",
    ImageURL: "CSGOPlayerImages/seized.jpg",
  },
  {
    PlayerId: 9565,
    NameFirst: "Alexandre",
    NameLast: "Pianaro",
    CurrentHandle: "bodyy",
    CountryCode: "fr",
    TotalUSDPrize: "342199.54",
    ImageURL: "CSGOPlayerImages/bodyy.jpg",
  },
  {
    PlayerId: 5035,
    NameFirst: "Philip",
    NameLast: "Aistrup",
    CurrentHandle: "aizy",
    CountryCode: "dk",
    TotalUSDPrize: "334996.67",
    ImageURL: "CSGOPlayerImages/aizy.jpg",
  },
];
